management:
  endpoint:
    shutdown:
      enabled: true

spring:
  datasource:
    url: jdbc:mysql://mysqldb:3306/student-service
    username: root
    password: root
    hibernate:
      ddl-auto: update
server:
  port: 8080
