name: build and push microservices


on:
  pull_request:
    branches: [ "master" ]
  push :
    branches: [ "master" ]
jobs:
  build:
    strategy:
      matrix:
        image_name: [ "student-service", "department-service"]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
           fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven ${{matrix.image_name}}
        working-directory: ${{matrix.image_name}}
        run: mvn -B clean package --file pom.xml

      - name: Scan with Sonarqube  ${{matrix.image_name}}
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: ${{matrix.image_name}}/src
          args: >
            -Dsonar.projectKey=${{matrix.image_name}}
        env:
            SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
            SONAR_HOST_URL: ${{ secrets.SONARQUBE_HOST }}

      - name: Dockerized & Push Docker Image ${{matrix.image_name}}
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
            image: ${{ secrets.DOCKER_USERNAME }}/${{matrix.image_name}}
            tags: latest
            directory: ${{matrix.image_name}}
            registry: docker.io
            dockerfile: ${{matrix.image_name}}/Dockerfile
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
