name: build and push microservices


on:
  pull_request:
    branches: [ "master" ]
  push :
    branches: [ "master" ]
jobs:
  build:
    strategy:
      matrix:
        image_name: [ "student-service" ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven ${{matrix.image_name}}
        working-directory: ${{matrix.image_name}}
        run: mvn -B clean package --file pom.xml

      - name: Test ${{matrix.image_name}}
        working-directory: ${{matrix.image_name}}
        run: mvn -B test --file pom.xml

      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build and push ${{ matrix.image_name }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.image_name }}
          push: true
          image: ${{ secrets.DOCKER_USERNAME }}/${{matrix.image_name}}
          tags: ${{ matrix.image_name }}:v1.0.0