name: build and push microservices


on:
  pull_request:
    branches: [ "master" ]
  push :
    branches: [ "master" ]
jobs:
  build:
    strategy:
      matrix:
        image_name: [ "student-service", "department-service"]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven ${{matrix.image_name}}
        working-directory: ${{matrix.image_name}}
        run: mvn -B clean package --file pom.xml

      - name: Test ${{matrix.image_name}}
        working-directory: ${{matrix.image_name}}
        run: mvn -B test --file pom.xml

      - name: SonarQube Scan
        uses: kitabisa/sonarqube-action@v1.2.0
        env:
            SONAR_SCANNER_OPTS: -X
        with:
            host: ${{ secrets.SONARQUBE_HOST }}
            login: ${{ secrets.SONARQUBE_TOKEN }}
            projectBaseDir: ${{matrix.image_name}}
            projectKey: ${{matrix.image_name}}

      - name: Dockerized & Push Docker Image ${{matrix.image_name}}
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
            image: ${{ secrets.DOCKER_USERNAME }}/${{matrix.image_name}}
            tags: latest
            directory: ${{matrix.image_name}}
            registry: docker.io
            dockerfile: ${{matrix.image_name}}/Dockerfile
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
